spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: "@Kanekipass12"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
